adminapp/urls.py
from django.urls import path, re_path

import adminapp.views as adminapp


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<pk>', adminapp.user_update, name='user_update'),
    path('users/delete/<pk>', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    re_path(r'^products/create/category/(?P<pk>\d+)/$', adminapp.ProductCreateView.as_view(), name='product_create'),
    re_path(r'^products/read/category/(?P<pk>\d+)/$', adminapp.ProductListView.as_view(), name='products'),
    path('products/read/<pk>', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<pk>', adminapp.product_update, name='product_update'),
    re_path(r'^products/delete/(?P<pk>\d+)/$', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path

from mainapp import views as mainapp


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    # path('subadmin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
   re_path(r'^order/', include('ordersapp.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
    import debug_toolbar

    # urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    # urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):

    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.db import connection

from adminapp.forms import ShopUserAdminEditForm, ProductEditForm, ProductCategoryEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    paginate_by = 3

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Админка/Пользователи'
        return context


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = ShopUserRegisterForm()

    content = {
        'update_form': user_form
    }
    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)
    content = {
        'update_form': edit_form
    }
    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    user_item = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        if user_item.is_active:
            user_item.is_active = False
        else:
            user_item.is_active = True
        user_item.save()
        return HttpResponseRedirect(reverse('admin:users'))

    content = {
        'user_to_delete': user_item
    }
    return render(request, 'adminapp/user_delete.html', content)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:categories')
    # fields = '__all__'
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/создание'
        return context


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    categories_list = ProductCategory.objects.all().order_by('-is_active')
    content = {
        'objects': categories_list
    }
    return render(request, 'adminapp/categories.html', content)


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:categories')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категория/Обновить'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1-discount/100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)
        return super().form_valid(form)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('adminapp:categories')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        category_pk = self.kwargs['pk']
        # print(category_pk)
        return queryset.filter(category__pk=category_pk)

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_pk = self.kwargs['pk']
        category_item = get_object_or_404(ProductCategory, pk=category_pk)
        context_data['category'] = category_item
        return context_data


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_create.html'
    form_class = ProductEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_pk = self.kwargs['pk']
        category_item = get_object_or_404(ProductCategory, pk=category_pk)
        context_data['category'] = category_item
        return context_data

    def get_success_url(self):
        category_pk = self.kwargs['pk']
        success_url = reverse('adminapp:products', args=[category_pk])
        return success_url


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = 'Админка/Обновить'
    product_item = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        update_form = ProductEditForm(request.POST, request.FILES, instance=product_item)
        if update_form.is_valid():
            update_form.save()
            return HttpResponseRedirect(reverse('admin:products', args=[pk]))
    else:
        update_form = ProductEditForm(instance=product_item)

    content = {
        'title': title,
        'update_form': update_form,
        'category': product_item.category
    }
    return render(request, 'adminapp/product_update.html', content)


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def delete(self, *args, **kwargs):
        object = self.get_object()
        if object.is_active:
            object.is_active = False
        else:
            object.is_active = True  # потестить что будет если будет FALSE
        object.save()
        return HttpResponseRedirect(reverse('adminapp:products', args=[object.category_id]))

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    {% endblock %}
</head>

<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>

    {% block menu %}
    <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
    </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
</div>
</body>

<!--интересеный факт, при просмотре страницы в Safari, верстка ломается, при открытии в Хроме, с версткой все Ок-->
<!--Проверить и дать на тестирвоание-->

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href="{% url 'admin:category_create' %}">
        новая категория
      </a>
    </button>

    {% for object in objects %}
      <div class="category_record"> {% if not object.is_active %}not_active{% endif %}
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href="{% url 'admin:products' object.pk %}">
              товары категории
            </a>
          </button>
          <button>
            <a href="{% url 'admin:category_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:category_delete' object.pk %}">
              удалить
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|capfirst }}
<!--          если оставить как  title, то каждое новое слово будет выводиться
с большой буквы на странице категорий в админке-->
<!--          {{ object.description|title }}-->
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        Уверены, что хотите удалить категорию <strong>{{object.name }}</strong>
        <form action="{% url 'admin:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="form-control" value="удалить">
        </form>
        <button class="btn btn_success">
            <a href="{% url 'admin:categories' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form action="" class="form_horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="form-control" value="сохранить">
        </form>
        <button class="btn btn_round form_control last">
            <a href="{% url 'admin:categories' %}">
                к списку категорий
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_create.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form action="" class="form_horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="form-control" value="сохранить">
        </form>
        <button class="btn btn_round form_control last">
            <a href="{% url 'admin:products' category.pk %}">
                к списку товаров
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        Уверены, что хотите удалить товар <strong>{{object.name }}</strong>
        <form action="{% url 'admin:product_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="form-control" value="удалить">
        </form>
        <button class="btn btn_success">
            <a href="{% url 'admin:products' object.category_id %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_read.html
<!--# если эту страницу перенести на папку выше, то кнопка "подробнее" не будет работать, будет ошибка-->
<!--оставить здесь комментарий, без правильного комментирования, чтобы это было видно на странице товара, тоже будет как дефект-->


{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ object.category.name|title }} / {{ object.name|title }}</strong>
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ object.price }} руб</p>
      <b>количество</b>
      <p>{{ object.quantity }}</p>
      <b>в каталоге</b>
      <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href={% url 'admin:product_update' object.pk %}>
            редактировать
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'admin:product_delete' object.pk %}>
            удалить
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'admin:products' object.category.pk %}>
            назад
          </a>
        </button>
      </p>
    </div>
    <div class="product_desc">
      <b>краткая информация</b>
      <p>{{ object.short_desc }}</p>
      <br><br>
      <b>подробная информация</b>
      <p>{{ object.description }}</p>
    </div>
  </div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form action="" class="form_horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="form-control" value="сохранить">
        </form>
        <button class="btn btn_round form_control last">
            <a href="{% url 'admin:products' category.pk %}">
                к списку товаров
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href="{% url 'admin:product_create' category.pk %}">новый продукт</a>
    </button>

    {% for object in object_list %}
      <div class="product_record {% if not object.is_active %}not_active{% endif %}">
<!--        <img src="/media/{{object.image|default:'products_images/default.png'}}" alt="{{ object.name }}">-->
        <img src="{{ object.image|media_folder_product }}" alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href="{% url 'admin:product_read' object.pk %}">
              подробнее
            </a>
          </button>
          <button>
            <a href="{% url 'admin:product_update' object.pk %}">
              редактировать
            </a>
          </button>
          <button>
            <a href="{% url 'admin:product_delete' object.pk %}">
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {% if object.is_active %} удалить {% else %} восстановить {% endif %}
<!--    можно раскоментировать и тогда будет дублироваться имя пользователя для удаления-->
<!--    {{ user_to_delete.username }}-->
    {% if user_to_delete.first_name %}
      <b>{{ user_to_delete.first_name|title }}</b>
      {% if user_to_delete.last_name %}
        {{ user_to_delete.last_name|title }}
      {% endif %}
    {% endif %}
    ?
    <form action="{% url 'admin:user_delete' user_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      {% if user_to_delete.is_active %}
        <input class="btn btn-danger" type="submit" value="удалить">
      {% else %}
        <input class="btn btn-primary" type="submit" value="восстановить">
      {% endif %}
<!--      <input class="btn btn-danger" type="submit" value="удалить">-->
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:users' %}"> к списку пользователей </a>
    </button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="users_list">
        <button class="new_user">
            <a href= "{% url 'admin:user_create' %}">
                новый пользователь
            </a>
        </button>
        {% for object in object_list %}
            <div
                    class="user_record {% if not object.is_active %} not_active {% endif %}">
<!--                    # если без аблонного фильтра своего из my_tags -> media_folder_users-->
<!--                <img src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"-->
                <img src="{{ object.avatar|media_folder_users }}" alt="{{ object.username }}">
                <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                        <button>
                            <a href="{% url 'admin:user_update' object.pk %}"> редактировать
                            </a>
                        </button>
                        <button>
                            <a href="{% url 'admin:user_delete' object.pk %}">
                                {% if object.is_active %}
                                удалить
                                {% else %}
                                восстановить
                                {% endif %}
                            </a>
                        </button>
                </div>
                    <div class="user_name">
<!--                        <p><strong>{{ object.username }}</strong></p>-->
                        <p><strong>{{ object.username|capitalize_name_user }}</strong></p>
                        <p>
                            {% if object.first_name %}
                                <b>{{ object.first_name|title }}</b>
                                {% if object.last_name %}
                                    <p>{{ object.last_name|title }}</p>
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>

                    <div class="user_age">
                        age:<br>
                        {{ object.age }} лет
                    </div>

                    <div class="user_email">
                        email:<br>
                        {{ object.email }}
                    </div>

                    <div class="user_lastlogin">
                        logged:<br>
                        {{ object.last_login }}
                    </div>
            </div>
        {% endfor%}
    </div>
{% endblock %}