authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify')
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
    path('remove/ajax/<int:pk>/', basketapp.basket_remove_ajax, name='remove_ajax'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path

from mainapp import views as mainapp


urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    # path('subadmin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
   re_path(r'^order/', include('ordersapp.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
    import debug_toolbar

    # urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    # urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from mainapp import views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>', mainapp.products, name='category'),
    path('category/<int:pk>/<page>/', mainapp.products, name='page'),
    path('product/<int:pk>', mainapp.product, name='product'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='имя')
    description = models.TextField(verbose_name='описание')
    is_active = models.BooleanField(default=True, verbose_name='активна', db_index=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='products_images', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=120, verbose_name='краткое описание', )
    description = models.TextField(verbose_name='описание', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='цена', )
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество на складе')
    is_active = models.BooleanField(default=True, verbose_name='продукт активен', db_index=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

mainapp/views.py
import random
import datetime
import os
import json

from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from django.core.cache import cache
from django.conf import settings
from django.views.decorators.cache import cache_page, never_cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from mainapp.models import ProductCategory, Product

JSON_PATH = 'mainapp/json'


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


@never_cache
def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
    if products is None:
        products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
        cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_ordered_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', errors='ignore') as infile:
        return json.load(infile)


def get_hot_product():
    product_list = Product.objects.all()
    # product_list = Product.objects.filter(is_active=True, category__is_active=True)  # если много категорий, то
    # при открытии раздела Продукты появляется ошибк аraise ValueError("Sample larger than population or is negative")
    # ValueError: Sample larger than population or is negative
    return random.sample(list(product_list), 1)[0]


def get_same_products(hot_product):
    return Product.objects.filter(category__pk=hot_product.category.pk).exclude(pk=hot_product.pk)[:3]


def main(request):
    title = 'главная'
    products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')[:3]
    content = {
        'title': title,
        'products': products}
    return render(request, 'mainapp/index.html', content)


# @cache_page(3600)  # uncomment in case I need to cache the products page
def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = get_links_menu()

    if pk is not None:
        if pk == 0:
            category = {'name': 'все', 'pk': 0}
            products = Product.objects.all().order_by('price')

        else:
            category = get_category(pk)
            products = Product.objects.filter(Q(category__pk=1) | Q(category__pk=2))

        paginator = Paginator(products, 2)  # отображение количества товаров на странице
        try:
            product_paginator = paginator.page(page)
        except PageNotAnInteger:
            product_paginator = paginator.page(1)  # Если польз ввел некоректный номер страницы, вывод первой стр
        except EmptyPage:
            product_paginator = paginator.page(paginator.num_pages)  # return last page to a user

        content = {
            'title': title,
            'links_menu': links_menu,
            'products': product_paginator,
            'category': category,
            # 'basket': basket
        }

        return render(request, 'mainapp/products_list.html', content)
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
        # 'basket': get_basket(request.user),
        'hot_product': hot_product,
    }
    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'
    content = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk)
    }
    return render(request, 'mainapp/product.html', content)


def contacts(request):
    title = 'о нас'
    visit_date = datetime.datetime.now()
    locations = []
    file_path = os.path.join(settings.BASE_DIR, 'contacts.json')
    with open(file_path) as file_contacts:
        locations = json.load(file_contacts)
    content = {
        'title': title,
        'visit_date': visit_date,
        'locations': locations,
    }
    return render(request, 'mainapp/contacts.html', content)


def products_all(request):
    links_menu = [
        {'href': 'products_all', 'name': 'все'},
        {'href': 'products_home', 'name': 'дом'},
        {'href': 'products_office', 'name': 'офис'},
        {'href': 'products_modern', 'name': 'модерн'},
        {'href': 'products_classic', 'name': 'классика'},
    ]
    content = {
        'title': 'Все продукты',
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/products.html', content)


def products_home(request):
    links_menu = [
        {'href': 'products_all', 'name': 'все'},
        {'href': 'products_home', 'name': 'дом'},
        {'href': 'products_office', 'name': 'офис'},
        {'href': 'products_modern', 'name': 'модерн'},
        {'href': 'products_classic', 'name': 'классика'},
    ]
    content = {
        'title': 'Дом',
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/products.html', content)


def products_office(request):
    links_menu = [
        {'href': 'products_all', 'name': 'все'},
        {'href': 'products_home', 'name': 'дом'},
        {'href': 'products_office', 'name': 'офис'},
        {'href': 'products_modern', 'name': 'модерн'},
        {'href': 'products_classic', 'name': 'классика'},
    ]
    content = {
        'title': 'Офис',
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/products.html', content)


def products_modern(request):
    links_menu = [
        {'href': 'products_all', 'name': 'все'},
        {'href': 'products_home', 'name': 'дом'},
        {'href': 'products_office', 'name': 'офис'},
        {'href': 'products_modern', 'name': 'модерн'},
        {'href': 'products_classic', 'name': 'классика'},
    ]
    content = {
        'title': 'Модерн',
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/products.html', content)


def products_classic(request):
    links_menu = [
        {'href': 'products_all', 'name': 'все'},
        {'href': 'products_home', 'name': 'дом'},
        {'href': 'products_office', 'name': 'офис'},
        {'href': 'products_modern', 'name': 'модерн'},
        {'href': 'products_classic', 'name': 'классика'},
    ]
    content = {
        'title': 'Класика',
        'links_menu': links_menu,
    }
    return render(request, 'mainapp/products.html', content)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|capfirst }}
        {% endblock %}
    </title>

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
    <div class="container">
        {% block menu %}
            <div class="hero-white">
                <div class="header clearfix">
                    <a href="/" class="logo"></a>
                    {% include 'mainapp/includes/inc_main_menu.html' %}
                </div>
            </div>
        {% endblock %}
        <div class="content">
        {% block content %}

        {% endblock %}
        </div>


        <div class="clr"></div>

    </div>

    {% block footer%}

        <div class="footer">
            <div class="clearfix">
                <div class="text-footer">
                    <h3>контакты</h3>
                </div>
                <div class="text-footer">
                    <h3>полезная информация</h3>
                </div>
                <div class="text-footer clearfix">
                    <h3>Оставайтесь на связи</h3>
                    <p>Подписаться на новости и рассылки</p>
                    <form>
                        <input type="email" name="email" placeholder="ваш email">
                        <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                    </form>
                </div>
            </div>
            <p class="small">&copy; GB {% now "Y-M-Date" %}</p>
            <div class="social">
                <a href="#" class="social1"></a>
                <a href="#" class="social2"></a>
                <a href="#" class="social3"></a>
                <a href="#" class="social4"></a>
            </div>
            <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
        </div>
    {% endblock %}

</body>
</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}

{% block menu %}
<div class="hero">
    <div class="header clearfix">
        <a href="/" class="logo"></a>
        {% include 'mainapp/includes/inc_main_menu.html' %}
        <a href="#" class="search"></a>
        <a href="#" class="basket"></a>
    </div>
    <h1>наши контакты</h1>
</div>
{% endblock %}

{% block content %}
<div class="location">
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
    <div class="location-1">
        <i class="fa fa-map-marker fa-5x"></i>
        <h4>Москва</h4>
        <div class="contacts">
            <h5>Телефон</h5>
            <p>+7-888-888-8888</p>
        </div>
        <div class="contacts">
            <h5>Email</h5>
            <p>info@geekshop.ru</p>
        </div>
        <div class="contacts">
            <h5>Адрес</h5>
            <p>В пределах МКАД</p>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html'%}
{% load static %}
from mainapp.models import ProductCategory, Product


{% block menu %}
<div class="slider">
    <div class="header clearfix">
        <a href="/" class="logo"></a>
        {% include 'mainapp/includes/inc_main_menu.html' %}
        <a href="#" class="search"></a>
    </div>
    <div class="text-slider">
        <h3 class="green">тенденции</h3>
        <h3 class="big"> удобные стулья</h3>
        <p>Новый уровень комфорта. Отличные характеристики.</p>
        <a href="#" class="button-order">заказать <img src="/static/img/arrow.png" alt=""></a>
    </div>
    <div class="navi">
        <a href="#"></a><a href="#"></a><a href="#"></a>
    </div>
</div>
{% endblock %}

{{ user.first_name|title}} {{ user.last_name}}

{% block content %}
    <div class="featured">
        <div class="featured-menu"><a class="active" href="#">Популярные</a><a href="#">Новинки</a></div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix"></div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="{% url 'basket:add' product.pk %}"><img src="/media/{{ product.image }}" alt="{{ product.alt }}">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="{{ product.alt }}">
                            <h4>Название: {{ product.name }}</h4>
                            <p>Короткое описание: {{ product.short_desc }} </p>
                            <p>Цена: {{ product.price }} </p>
                            <p>Наличие на складе: {{ product.quantity }} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}"
                         alt="{{ product.short_desc }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="вариант 1">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="вариант 2">
                        </a>
                    </div>
                    <div class="block">
                        <a href="#">
                            <img src="/media/{{ product.image }}" alt="вариант 3">
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>

    </div>

    <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        <a href="/" class="logo"></a>
        {% include 'mainapp/includes/inc_main_menu.html' %}
        <a href="#" class="search"></a>
        <a href="#" class="basket"></a>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ hot_product.image }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{hot_product.name }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price"> {{hot_product.price|floatformat:1 }} <span>руб</span></p>
            <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>{{hot_product.short_desc }}</p>
            </div>
        </div>
    </div>

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="related-products clearfix">
            {% for product in same_products %}
                <div class="block">
                    <a href="{% url 'basket:add' product.pk %}"><img src="/media/{{ product.image }}" alt="{{ product.alt}}">
                        <div class="text">
                            <img src="/static/img/icon-hover.png" alt="img">
                            <h3>Категория: {{ product.category.name }}</h3>
                            <h4>Название: {{ product.name }}</h4>
                            <p>Короткое описание: {{ product.short_desc }}</p>
                            <p>Цена: {{ product.price }} </p>
                            <p>Наличие на складе: {{ product.quantity }} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
<div class="hero-white">
    <div class="header clearfix">
        <a href="/" class="logo"></a>
        {% include 'mainapp/includes/inc_main_menu.html' %}
        <a href="#" class="search"></a>
        <a href="#" class="basket"></a>
    </div>
</div>
{% endblock %}


{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>Категория: "{{ category.name|title }}"</h2>
                    <div class="paginator">
                      {% if products.has_previous %}
                        <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                          <
                        </a>
                      {% endif %}
                      <span class="current"> страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
                      {% if products.has_next %}
                        <a href="{% url 'products:page' category.pk products.next_page_number %}">
                          >
                        </a>
                      {% endif %}
                    </div>

            </div>
            <div class="category-products clearfix">
                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p> {{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>
{% endblock %}